// This file is auto-generated by generate-gallery.js. DO NOT EDIT MANUALLY.
const imageData = [
    {
        "category": "basement",
        "src": "../images/projects/all/small/lashln/basement/new_basement(1)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/basement/new_basement(1)_large.webp",
        "alt": "New Basement - Basement"
    },
    {
        "category": "basement",
        "src": "../images/projects/all/small/lashln/basement/new_basement(2)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/basement/new_basement(2)_large.webp",
        "alt": "New Basement - Basement"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(1)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(1)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(2)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(2)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(3)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(3)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(4)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(4)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(5)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(5)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(6)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(6)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(7)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(7)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(8)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(8)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(9)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(9)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/beacon/bathroom/new_bathroom(2).webp",
        "largeSrc": "../images/projects/beacon/bathroom/new_bathroom(2).webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/beacon/bathroom/new_bathroom(6).webp",
        "largeSrc": "../images/projects/beacon/bathroom/new_bathroom(6).webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/wynward/bathroom/new_bathroom(1).webp",
        "largeSrc": "../images/projects/wynward/bathroom/new_bathroom(1).webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/wynward/bathroom/new_bathroom(2).webp",
        "largeSrc": "../images/projects/wynward/bathroom/new_bathroom(2).webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/wynward/bathroom/new_bathroom(3).webp",
        "largeSrc": "../images/projects/wynward/bathroom/new_bathroom(3).webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/wynward/bathroom/new_bathroom(4).webp",
        "largeSrc": "../images/projects/wynward/bathroom/new_bathroom(4).webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bedroom",
        "src": "../images/projects/beacon/bedroom/new_bedroom(1).webp",
        "largeSrc": "../images/projects/beacon/bedroom/new_bedroom(1).webp",
        "alt": "New Bedroom - Bedroom"
    },
    {
        "category": "bedroom",
        "src": "../images/projects/beacon/bedroom/new_bedroom(2).webp",
        "largeSrc": "../images/projects/beacon/bedroom/new_bedroom(2).webp",
        "alt": "New Bedroom - Bedroom"
    },
    {
        "category": "closet",
        "src": "../images/projects/all/small/lashln/closet/new_closet(1)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/closet/new_closet(1)_large.webp",
        "alt": "New Closet - Closet"
    },
    {
        "category": "closet",
        "src": "../images/projects/all/small/lashln/closet/new_closet(2)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/closet/new_closet(2)_large.webp",
        "alt": "New Closet - Closet"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/beacon/kitchen/new_kitchen(1).webp",
        "largeSrc": "../images/projects/beacon/kitchen/new_kitchen(1).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/beacon/kitchen/new_kitchen(2).webp",
        "largeSrc": "../images/projects/beacon/kitchen/new_kitchen(2).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/beacon/kitchen/new_kitchen(3).webp",
        "largeSrc": "../images/projects/beacon/kitchen/new_kitchen(3).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/beacon/kitchen/new_kitchen(4).webp",
        "largeSrc": "../images/projects/beacon/kitchen/new_kitchen(4).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/wynward/kitchen/front_page.webp",
        "largeSrc": "../images/projects/wynward/kitchen/front_page.webp",
        "alt": "Front Page - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/wynward/kitchen/new_kitchen(1).webp",
        "largeSrc": "../images/projects/wynward/kitchen/new_kitchen(1).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/wynward/kitchen/new_kitchen(2).webp",
        "largeSrc": "../images/projects/wynward/kitchen/new_kitchen(2).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/wynward/kitchen/new_kitchen(3).webp",
        "largeSrc": "../images/projects/wynward/kitchen/new_kitchen(3).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "living_room",
        "src": "../images/projects/beacon/living_room/new_living_room(1).webp",
        "largeSrc": "../images/projects/beacon/living_room/new_living_room(1).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/beacon/living_room/new_living_room(2).webp",
        "largeSrc": "../images/projects/beacon/living_room/new_living_room(2).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/beacon/living_room/new_living_room(3).webp",
        "largeSrc": "../images/projects/beacon/living_room/new_living_room(3).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/beacon/living_room/new_living_room(4).webp",
        "largeSrc": "../images/projects/beacon/living_room/new_living_room(4).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/beacon/living_room/new_living_room(5).webp",
        "largeSrc": "../images/projects/beacon/living_room/new_living_room(5).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/beacon/living_room/new_living_room(6).webp",
        "largeSrc": "../images/projects/beacon/living_room/new_living_room(6).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_dinning_room.webp",
        "largeSrc": "../images/projects/wynward/living_room/new_dinning_room.webp",
        "alt": "New Dinning Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_enclosed_deck.webp",
        "largeSrc": "../images/projects/wynward/living_room/new_enclosed_deck.webp",
        "alt": "New Enclosed Deck - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_living_room(1).webp",
        "largeSrc": "../images/projects/wynward/living_room/new_living_room(1).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_living_room(2).webp",
        "largeSrc": "../images/projects/wynward/living_room/new_living_room(2).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_living_room(3).webp",
        "largeSrc": "../images/projects/wynward/living_room/new_living_room(3).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_living_room(4).webp",
        "largeSrc": "../images/projects/wynward/living_room/new_living_room(4).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_living_room(5).webp",
        "largeSrc": "../images/projects/wynward/living_room/new_living_room(5).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_living_room(6).webp",
        "largeSrc": "../images/projects/wynward/living_room/new_living_room(6).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "small",
        "src": "../images/projects/beacon/bathroom/small/new_bathroom(1)_small.webp",
        "largeSrc": "../images/projects/beacon/bathroom/new_bathroom(1)_large.webp",
        "alt": "New Bathroom - Small"
    },
    {
        "category": "small",
        "src": "../images/projects/beacon/bathroom/small/new_bathroom(3)_small.webp",
        "largeSrc": "../images/projects/beacon/bathroom/new_bathroom(3)_large.webp",
        "alt": "New Bathroom - Small"
    },
    {
        "category": "small",
        "src": "../images/projects/beacon/bathroom/small/new_bathroom(4)_small.webp",
        "largeSrc": "../images/projects/beacon/bathroom/new_bathroom(4)_large.webp",
        "alt": "New Bathroom - Small"
    },
    {
        "category": "small",
        "src": "../images/projects/beacon/bathroom/small/new_bathroom(5)_small.webp",
        "largeSrc": "../images/projects/beacon/bathroom/new_bathroom(5)_large.webp",
        "alt": "New Bathroom - Small"
    },
    {
        "category": "small",
        "src": "../images/projects/beacon/kitchen/small/new_kitchen(6)_small.webp",
        "largeSrc": "../images/projects/beacon/kitchen/new_kitchen(6)_large.webp",
        "alt": "New Kitchen - Small"
    },
    {
        "category": "small",
        "src": "../images/projects/beacon/random/small/074A3176_edit copy_small.webp",
        "largeSrc": "../images/projects/beacon/random/074A3176_edit copy_large.webp",
        "alt": "074A3176 Edit Copy - Small"
    },
    {
        "category": "small",
        "src": "../images/projects/beacon/random/small/074A3185_small.webp",
        "largeSrc": "../images/projects/beacon/random/074A3185_large.webp",
        "alt": "074A3185 - Small"
    },
    {
        "category": "small",
        "src": "../images/projects/beacon/random/small/074A3190_small.webp",
        "largeSrc": "../images/projects/beacon/random/074A3190_large.webp",
        "alt": "074A3190 - Small"
    },
    {
        "category": "small",
        "src": "../images/projects/beacon/random/small/074A3229_small.webp",
        "largeSrc": "../images/projects/beacon/random/074A3229_large.webp",
        "alt": "074A3229 - Small"
    }
];