// This file is auto-generated by generate-gallery.js. DO NOT EDIT MANUALLY.
const imageData = [
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/condo/bathroom/new_bathroom(1)_small.webp",
        "largeSrc": "../images/projects/all/large/condo/bathroom/new_bathroom(1)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/condo/bathroom/new_bathroom(2)_small.webp",
        "largeSrc": "../images/projects/all/large/condo/bathroom/new_bathroom(2)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/condo/bathroom/new_bathroom(3)_small.webp",
        "largeSrc": "../images/projects/all/large/condo/bathroom/new_bathroom(3)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/condo/bathroom/new_bathroom(4)_small.webp",
        "largeSrc": "../images/projects/all/large/condo/bathroom/new_bathroom(4)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/condo/bathroom/new_bathroom(5)_small.webp",
        "largeSrc": "../images/projects/all/large/condo/bathroom/new_bathroom(5)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/condo/bathroom/new_bathroom(6)_small.webp",
        "largeSrc": "../images/projects/all/large/condo/bathroom/new_bathroom(6)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(1)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(1)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(2)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(2)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(3)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(3)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(4)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(4)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(5)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(5)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(6)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(6)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(7)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(7)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(8)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(8)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/lashln/bathroom/new_bathroom(9)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/bathroom/new_bathroom(9)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/rocky_springs/bathroom/new_bathroom(1)_small.webp",
        "largeSrc": "../images/projects/all/large/rocky_springs/bathroom/new_bathroom(1)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/rocky_springs/bathroom/new_bathroom(2)_small.webp",
        "largeSrc": "../images/projects/all/large/rocky_springs/bathroom/new_bathroom(2)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/rocky_springs/bathroom/new_bathroom(3)_small.webp",
        "largeSrc": "../images/projects/all/large/rocky_springs/bathroom/new_bathroom(3)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/all/small/rocky_springs/bathroom/new_bathroom(4)_small.webp",
        "largeSrc": "../images/projects/all/large/rocky_springs/bathroom/new_bathroom(4)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/beacon/bathroom/small/new_bathroom(1)_small.webp",
        "largeSrc": "../images/projects/beacon/bathroom/new_bathroom(1)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/beacon/bathroom/new_bathroom(2).webp",
        "largeSrc": "../images/projects/beacon/bathroom/new_bathroom(2).webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/beacon/bathroom/small/new_bathroom(3)_small.webp",
        "largeSrc": "../images/projects/beacon/bathroom/new_bathroom(3)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/beacon/bathroom/small/new_bathroom(4)_small.webp",
        "largeSrc": "../images/projects/beacon/bathroom/new_bathroom(4)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/beacon/bathroom/small/new_bathroom(5)_small.webp",
        "largeSrc": "../images/projects/beacon/bathroom/new_bathroom(5)_large.webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/beacon/bathroom/new_bathroom(6).webp",
        "largeSrc": "../images/projects/beacon/bathroom/new_bathroom(6).webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/wynward/bathroom/new_bathroom(1).webp",
        "largeSrc": "../images/projects/wynward/bathroom/new_bathroom(1).webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/wynward/bathroom/new_bathroom(2).webp",
        "largeSrc": "../images/projects/wynward/bathroom/new_bathroom(2).webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/wynward/bathroom/new_bathroom(3).webp",
        "largeSrc": "../images/projects/wynward/bathroom/new_bathroom(3).webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bathroom",
        "src": "../images/projects/wynward/bathroom/new_bathroom(4).webp",
        "largeSrc": "../images/projects/wynward/bathroom/new_bathroom(4).webp",
        "alt": "New Bathroom - Bathroom"
    },
    {
        "category": "bedroom",
        "src": "../images/projects/all/small/condo/bedroom/new_bedroom(1)_small.webp",
        "largeSrc": "../images/projects/all/large/condo/bedroom/new_bedroom(1)_large.webp",
        "alt": "New Bedroom - Bedroom"
    },
    {
        "category": "bedroom",
        "src": "../images/projects/all/small/condo/bedroom/new_bedroom(2)_small.webp",
        "largeSrc": "../images/projects/all/large/condo/bedroom/new_bedroom(2)_large.webp",
        "alt": "New Bedroom - Bedroom"
    },
    {
        "category": "bedroom",
        "src": "../images/projects/all/small/rocky_springs/bedroom/new_bedroom(1)_small.webp",
        "largeSrc": "../images/projects/all/large/rocky_springs/bedroom/new_bedroom(1)_large.webp",
        "alt": "New Bedroom - Bedroom"
    },
    {
        "category": "bedroom",
        "src": "../images/projects/all/small/rocky_springs/bedroom/new_bedroom(2)_small.webp",
        "largeSrc": "../images/projects/all/large/rocky_springs/bedroom/new_bedroom(2)_large.webp",
        "alt": "New Bedroom - Bedroom"
    },
    {
        "category": "bedroom",
        "src": "../images/projects/all/small/rocky_springs/bedroom/new_bedroom(3)_small.webp",
        "largeSrc": "../images/projects/all/large/rocky_springs/bedroom/new_bedroom(3)_large.webp",
        "alt": "New Bedroom - Bedroom"
    },
    {
        "category": "bedroom",
        "src": "../images/projects/all/small/rocky_springs/bedroom/new_bedroom(4)_small.webp",
        "largeSrc": "../images/projects/all/large/rocky_springs/bedroom/new_bedroom(4)_large.webp",
        "alt": "New Bedroom - Bedroom"
    },
    {
        "category": "bedroom",
        "src": "../images/projects/all/small/rocky_springs/bedroom/new_bedroom(5)_small.webp",
        "largeSrc": "../images/projects/all/large/rocky_springs/bedroom/new_bedroom(5)_large.webp",
        "alt": "New Bedroom - Bedroom"
    },
    {
        "category": "bedroom",
        "src": "../images/projects/beacon/bedroom/new_bedroom(1).webp",
        "largeSrc": "../images/projects/beacon/bedroom/new_bedroom(1).webp",
        "alt": "New Bedroom - Bedroom"
    },
    {
        "category": "bedroom",
        "src": "../images/projects/beacon/bedroom/new_bedroom(2).webp",
        "largeSrc": "../images/projects/beacon/bedroom/new_bedroom(2).webp",
        "alt": "New Bedroom - Bedroom"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/all/small/condo/kitchen/new_kitchen(1)_small.webp",
        "largeSrc": "../images/projects/all/large/condo/kitchen/new_kitchen(1)_large.webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/all/small/condo/kitchen/new_kitchen(2)_small.webp",
        "largeSrc": "../images/projects/all/large/condo/kitchen/new_kitchen(2)_large.webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/all/small/condo/kitchen/new_kitchen(3)_small.webp",
        "largeSrc": "../images/projects/all/large/condo/kitchen/new_kitchen(3)_large.webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/all/small/condo/kitchen/new_kitchen(4)_small.webp",
        "largeSrc": "../images/projects/all/large/condo/kitchen/new_kitchen(4)_large.webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/all/small/little_river/kitchen/new_kitchen(1)_small.webp",
        "largeSrc": "../images/projects/all/large/little_river/kitchen/new_kitchen(1)_large.webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/all/small/little_river/kitchen/new_kitchen(2)_small.webp",
        "largeSrc": "../images/projects/all/large/little_river/kitchen/new_kitchen(2)_large.webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/all/small/little_river/kitchen/new_kitchen(3)_small.webp",
        "largeSrc": "../images/projects/all/large/little_river/kitchen/new_kitchen(3)_large.webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/all/small/little_river/kitchen/new_kitchen(4)_small.webp",
        "largeSrc": "../images/projects/all/large/little_river/kitchen/new_kitchen(4)_large.webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/beacon/kitchen/new_kitchen(1).webp",
        "largeSrc": "../images/projects/beacon/kitchen/new_kitchen(1).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/beacon/kitchen/new_kitchen(2).webp",
        "largeSrc": "../images/projects/beacon/kitchen/new_kitchen(2).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/beacon/kitchen/new_kitchen(3).webp",
        "largeSrc": "../images/projects/beacon/kitchen/new_kitchen(3).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/beacon/kitchen/new_kitchen(4).webp",
        "largeSrc": "../images/projects/beacon/kitchen/new_kitchen(4).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/beacon/kitchen/small/new_kitchen(6)_small.webp",
        "largeSrc": "../images/projects/beacon/kitchen/new_kitchen(6)_large.webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/wynward/kitchen/front_page.webp",
        "largeSrc": "../images/projects/wynward/kitchen/front_page.webp",
        "alt": "Front Page - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/wynward/kitchen/new_kitchen(1).webp",
        "largeSrc": "../images/projects/wynward/kitchen/new_kitchen(1).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/wynward/kitchen/new_kitchen(2).webp",
        "largeSrc": "../images/projects/wynward/kitchen/new_kitchen(2).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "kitchen",
        "src": "../images/projects/wynward/kitchen/new_kitchen(3).webp",
        "largeSrc": "../images/projects/wynward/kitchen/new_kitchen(3).webp",
        "alt": "New Kitchen - Kitchen"
    },
    {
        "category": "living_room",
        "src": "../images/projects/beacon/living_room/new_living_room(1).webp",
        "largeSrc": "../images/projects/beacon/living_room/new_living_room(1).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/beacon/living_room/new_living_room(2).webp",
        "largeSrc": "../images/projects/beacon/living_room/new_living_room(2).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/beacon/living_room/new_living_room(3).webp",
        "largeSrc": "../images/projects/beacon/living_room/new_living_room(3).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/beacon/living_room/new_living_room(4).webp",
        "largeSrc": "../images/projects/beacon/living_room/new_living_room(4).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/beacon/living_room/new_living_room(5).webp",
        "largeSrc": "../images/projects/beacon/living_room/new_living_room(5).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/beacon/living_room/new_living_room(6).webp",
        "largeSrc": "../images/projects/beacon/living_room/new_living_room(6).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_dinning_room.webp",
        "largeSrc": "../images/projects/wynward/living_room/new_dinning_room.webp",
        "alt": "New Dinning Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_enclosed_deck.webp",
        "largeSrc": "../images/projects/wynward/living_room/new_enclosed_deck.webp",
        "alt": "New Enclosed Deck - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_living_room(1).webp",
        "largeSrc": "../images/projects/wynward/living_room/new_living_room(1).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_living_room(2).webp",
        "largeSrc": "../images/projects/wynward/living_room/new_living_room(2).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_living_room(3).webp",
        "largeSrc": "../images/projects/wynward/living_room/new_living_room(3).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_living_room(4).webp",
        "largeSrc": "../images/projects/wynward/living_room/new_living_room(4).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_living_room(5).webp",
        "largeSrc": "../images/projects/wynward/living_room/new_living_room(5).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "living_room",
        "src": "../images/projects/wynward/living_room/new_living_room(6).webp",
        "largeSrc": "../images/projects/wynward/living_room/new_living_room(6).webp",
        "alt": "New Living Room - Living room"
    },
    {
        "category": "misc",
        "src": "../images/projects/all/small/condo/misc/new_stairs(1)_small.webp",
        "largeSrc": "../images/projects/all/large/condo/misc/new_stairs(1)_large.webp",
        "alt": "New Stairs - Misc"
    },
    {
        "category": "misc",
        "src": "../images/projects/all/small/lashln/basement/new_basement(1)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/basement/new_basement(1)_large.webp",
        "alt": "New Basement - Basement"
    },
    {
        "category": "misc",
        "src": "../images/projects/all/small/lashln/basement/new_basement(2)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/basement/new_basement(2)_large.webp",
        "alt": "New Basement - Basement"
    },
    {
        "category": "misc",
        "src": "../images/projects/all/small/lashln/closet/new_closet(1)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/closet/new_closet(1)_large.webp",
        "alt": "New Closet - Closet"
    },
    {
        "category": "misc",
        "src": "../images/projects/all/small/lashln/closet/new_closet(2)_small.webp",
        "largeSrc": "../images/projects/all/large/lashln/closet/new_closet(2)_large.webp",
        "alt": "New Closet - Closet"
    },
    {
        "category": "outdoor",
        "src": "../images/projects/all/small/condo/outdoor/new_outdoor_small.webp",
        "largeSrc": "../images/projects/all/large/condo/outdoor/new_outdoor_large.webp",
        "alt": "New Outdoor - Outdoor"
    }
];