# -----------------------------------------------------------------
# Netlify Configuration for Will's Remodel Website
# -----------------------------------------------------------------

#
# 1. Build Settings
#
[build]
  # This tells Netlify which folder contains the finished website.
  # Since your index.html is in the root, we use "."
  publish = "."


#
# 2. Redirect & Rewrite Rules (for Clean URLs)
#
# This section replaces the need for a separate _redirects file.
# The double brackets [[redirects]] indicate that this is an array, allowing for multiple rules.
# The "status = 200" means "rewrite the path without changing the URL in the browser."
#

# -- Main Pages --
[[redirects]]
  from = "/about"
  to = "/pages/about.html"
  status = 200

[[redirects]]
  from = "/our-projects"
  to = "/pages/our_projects.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/pages/gallery.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/pages/contact.html"
  status = 200
  
[[redirects]]
  from = "/thank-you"
  to = "/pages/thank_you.html"
  status = 200

# -- Individual Project Pages --
[[redirects]]
  from = "/projects/beacon"
  to = "/pages/projects/beacon.html"
  status = 200

[[redirects]]
  from = "/projects/lashln"
  to = "/pages/projects/lash_up_ln.html"
  status = 200

[[redirects]]
  from = "/projects/wynward"
  to = "/pages/projects/wynward.html"
  status = 200