# -----------------------------------------------------------------
# Netlify Configuration for Will's Remodel Website
# -----------------------------------------------------------------

#
# 1. Build Settings
#
[build]
  # This tells Netlify which folder contains the finished website.
  # Since your index.html is in the root, we use "."
  publish = "."


#
# 2. Redirect & Rewrite Rules (for Clean URLs)
#
# This section replaces the need for a separate _redirects file.
# The double brackets [[redirects]] indicate that this is an array, allowing for multiple rules.
# The "status = 200" means "rewrite the path without changing the URL in the browser."
#

# -- Main Pages --
[[redirects]]
  from = "/about"
  to = "/pages/about.html"
  status = 200

[[redirects]]
  from = "/our-projects"
  to = "/pages/our_projects.html"
  status = 200

[[redirects]]
  from = "/gallery"
  to = "/pages/gallery.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/pages/contact.html"
  status = 200
  
[[redirects]]
  from = "/thank-you"
  to = "/pages/thank_you.html"
  status = 200

# -- Individual Project Pages --
[[redirects]]
  from = "/projects/beacon"
  to = "/pages/projects/beacon.html"
  status = 200

[[redirects]]
  from = "/projects/lashln"
  to = "/pages/projects/lash_up_ln.html"
  status = 200

[[redirects]]
  from = "/projects/wynward"
  to = "/pages/projects/wynward.html"
  status = 200

[[headers]]
  # This rule applies to all pages on your site (/*).
  for = "/*"
  [headers.values]
    # UPDATED Content-Security-Policy to allow all necessary sources
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; script-src 'self' https://cdn.jsdelivr.net https://code.jquery.com https://cdnjs.cloudflare.com https://maps.googleapis.com; img-src 'self' data: https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://maps.gstatic.com *.googleapis.com *.ggpht.com; font-src 'self' https://cdn.jsdelivr.net; frame-src 'self' https://*.google.com;"

    # X-Content-Type-Options: Prevents the browser from trying to guess the content type of a file.
    # This stops attacks where a malicious file is disguised as something else.
    X-Content-Type-Options = "nosniff"

    # Referrer-Policy: Controls how much information is sent when a user clicks a link to another site.
    # 'strict-origin-when-cross-origin' is a modern, privacy-respecting default.
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Permissions-Policy: Controls which browser features can be used on your site.
    # This example disables features that are common privacy/security risks.
    Permissions-Policy = "midi=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), fullscreen=(), payment=()"