# -----------------------------------------------------------------
# Netlify Configuration for Will's Remodel Website
# -----------------------------------------------------------------

#
# 1. Build Settings
#
[build]
  # This tells Netlify which folder contains the finished website.
  # Since your index.html is in the root, we use "."
  publish = "."
