# Will-s_remodel/netlify.toml

# 1. Build Settings
[build]
  # This tells Netlify which folder contains the finished website.
  publish = "."

# 2. Header Settings
[[headers]]
  # This rule applies to all pages on your site
  for = "/*"
  [headers.values]
    # Corrected Content Security Policy
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdnjs.cloudflare.com; script-src 'self' https://www.googletagmanager.com 'unsafe-inline' https://cdn.jsdelivr.net https://code.jquery.com https://cdnjs.cloudflare.com https://maps.googleapis.com; connect-src 'self' https://www.google-analytics.com https://www.googletagmanager.com; img-src 'self' data: https://cdn.jsdelivr.net https://cdnjs.cloudflare.com https://maps.gstatic.com *.googleapis.com *.ggpht.com; font-src 'self' https://cdn.jsdelivr.net; frame-src 'self' https://www.google.com; frame-ancestors 'self';"
    
    # Other Security Headers
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "midi=(), sync-xhr=(), microphone=(), camera=(), magnetometer=(), gyroscope=(), fullscreen=(), payment=()"
